#!/bin/bash -eu
# © 2022–present Harald Rudell <harald.rudell@gmail.com> (https://haraldrudell.github.io/haraldrudell/)
# push
# macOS 12.3.1, Linux 5.13

if [ ! -d zbuild ]; then
  echo >&2 "./push must be run from parl project directory, where parl.go is"
  exit 1
fi

CMD1=(cd zbuild)
CMD2=(go run ./pushparl.go)
echo "(${CMD1[*]} && ${CMD2[*]})"

("${CMD1[@]}" && "${CMD2[@]}") || { X=$?; exit $X; }
echo "push completed successfully"
