#!/bin/bash -eu
# © 2022–present Harald Rudell <harald.rudell@gmail.com> (https://haraldrudell.github.io/haraldrudell/)
# tidy
# macOS 12.3.1, Linux 5.13
VERSION="tidy"\
"\n  version: 220412 parl: fix go work sync issues"\
"\nu do “go get -u”"
GoUpdate=(go get -u)
GoModTidy=(go mod tidy)
GoWorkSync=(go work sync)

echo -e "\n$VERSION"

Update=false
if [ $# -gt 0 ]; then for OPTION in "$@"; do
  if [ "$OPTION" = u ]; then
    Update=true
  else
    echo >&2 "Bad option: '$OPTION'"
    exit 1
  fi
done; fi

tidyAll() {
  tidyDirectory mains
  tidyDirectory pfs
  tidyDirectory pterm
  tidyDirectory sqliter

  # go mod tidy
  echo -e "\n${GoModTidy[*]}"
  "${GoModTidy[@]}" || return

  # go work sync
  echo -e "\n${GoWorkSync[*]}"
  "${GoWorkSync[@]}" || return
}

tidyDirectory() {
  local DIR="$1"
  local CMD=(cd "$DIR")
  local S="(${CMD[*]}"
  if $Update; then
    S+=" && ${GoUpdate[*]}"
  fi
  S+=" && ${GoModTidy[*]})"
  echo -e "\n$S"
  ("${CMD[@]}" && if $Update; then ${GoUpdate[*]}; fi && "${GoModTidy[@]}") || return
}

tidyAll || { X=$?; echo >&2 "status code: $X"; exit $X; }
echo -e "\ntidy completed successfully"
