/*
© 2022–present Harald Rudell <harald.rudell@gmail.com> (https://haraldrudell.github.io/haraldrudell/)
ISC License
*/

package parlca

import (
	"crypto/ecdsa"
	"crypto/x509"
	"encoding/pem"

	"github.com/haraldrudell/parl"
	"github.com/haraldrudell/parl/perrors"
)

// EcdsaPublicKey is container for public key in efficient binary form
//   - generated by [EcdsaPrivateKey.PublicKey] or [parl.PrivateKey.PublicKey]
type EcdsaPublicKey struct {
	ecdsa.PublicKey
}

// Algo returns algorithm [x509.ECDSA] “ECDSA”
func (key *EcdsaPublicKey) Algo() (algo x509.PublicKeyAlgorithm) {
	return x509.ECDSA
}

// DER returns public key as PKCS#1 ASN.1 DER
func (key *EcdsaPublicKey) DER() (publicKeyDer parl.PublicKeyDer, err error) {
	publicKeyDer, err = x509.MarshalPKIXPublicKey(&key.PublicKey)
	perrors.IsPF(&err, "x509.MarshalPKIXPublicKey %w", err)
	return
}

// DERe returns public key as PKCS#1 ASN.1 DER panic on error
func (key *EcdsaPublicKey) DERe() (publicKeyDer parl.PublicKeyDer) {
	var err error
	if publicKeyDer, err = key.DER(); err != nil {
		panic(err)
	}
	return
}

// PEM returns public key in text form “-----RSA PUBLIC KEY …”
func (key *EcdsaPublicKey) PEM() (pemBytes parl.PemBytes, err error) {
	block := pem.Block{
		Type: pemPublicKeyType,
	}
	if block.Bytes, err = key.DER(); err != nil {
		return
	}
	pemBytes = append([]byte(PemText()), pem.EncodeToMemory(&block)...)
	return
}

// PEMe returns public key in text form “-----RSA PUBLIC KEY …” panic on error
func (key *EcdsaPublicKey) PEMe() (pemBytes parl.PemBytes) {
	var err error
	if pemBytes, err = key.PEM(); err != nil {
		panic(err)
	}
	return
}
