/*
© 2022–present Harald Rudell <harald.rudell@gmail.com> (https://haraldrudell.github.io/haraldrudell/)
ISC License
*/

package parlca

import (
	"crypto/ed25519"
	"crypto/x509"
	"encoding/pem"

	"github.com/haraldrudell/parl"
	"github.com/haraldrudell/parl/parlca/calib"
	"github.com/haraldrudell/parl/perrors"
)

// Ed25519PublicKey is public Ed25519 key
//   - generated by [Ed25519PrivateKey.PublicKey] or
//     [parl.PrivateKey.PublicKey]
type Ed25519PublicKey struct {
	// Equal()
	ed25519.PublicKey
}

// Ed25519PublicKey is [parl.PublicKey]
var _ parl.PublicKey = &Ed25519PublicKey{}

// DER returns public key as PKCS#1 ASN.1 DER
func (key *Ed25519PublicKey) DER() (publicKeyDer parl.PublicKeyDer, err error) {
	if len(key.PublicKey) == 0 {
		err = perrors.New("Uninitialized ed25519 public key")
		return
	} else if len(key.PublicKey) != ed25519.PublicKeySize {
		err = perrors.Errorf("Bad ed25519 public key length: %d exp: %d", len(key.PublicKey), ed25519.PublicKeySize)
		return
	}
	var byts []byte
	if byts, err = x509.MarshalPKIXPublicKey(key.PublicKey); perrors.IsPF(&err, "x509.MarshalPKIXPublicKey %w", err) {
		return
	}
	publicKeyDer = byts
	return
}

// DERe returns public key as PKCS#1 ASN.1 DER panic on error
func (key *Ed25519PublicKey) DERe() (publicKeyDer parl.PublicKeyDer) {
	var err error
	if publicKeyDer, err = key.DER(); err != nil {
		panic(err)
	}
	return
}

// PEM returns public key in text form “-----PUBLIC KEY …”
func (key *Ed25519PublicKey) PEM() (pemBytes parl.PemBytes, err error) {
	block := pem.Block{
		Type: pemPublicKeyType,
	}
	if block.Bytes, err = key.DER(); err != nil {
		return
	}
	pemBytes = append([]byte(calib.PemText()), pem.EncodeToMemory(&block)...)
	return
}

// PEMe returns public key in text form “-----PUBLIC KEY …” panic on error
func (key *Ed25519PublicKey) PEMe() (pemBytes parl.PemBytes) {
	var err error
	if pemBytes, err = key.PEM(); err != nil {
		panic(err)
	}
	return
}

// Algo returns algorithm [x509.Ed25519] “Ed25519”
func (key *Ed25519PublicKey) Algo() (algo x509.PublicKeyAlgorithm) {
	return x509.Ed25519
}
